### ISSUE TITLE
TBX11K Tuberculosis Classification and Detection Challenge

### ISSUE THREAD

**Issue by junqiangchen** [yun-liu/yun-liu.github.io#1]
您好，

我在TBX11K上提交了测试集结果，参考了样例结果，但是还是出现以下错误，不知道问题出现在哪儿，有空还请您指点一下。
![image](https://github.com/yun-liu/yun-liu.github.io/assets/28638716/0c5d6dd4-cf4c-4744-bda4-8fbcb6ca646d)

谢谢！！
陈俊强

**Comment by yun-liu** [comment]
@junqiangchen 我刚才试了一下，server没有问题，应该是您数据格式的问题。

**Comment by junqiangchen** [comment]
> @junqiangchen 我刚才试了一下，server没有问题，应该是您数据格式的问题。

式的问题。

好的，确实是格式问题，现在已经解决了，谢谢！！
